### ISSUE TITLE
After a Noryx attack server raise a InvalidToken

### ISSUE THREAD

**Issue by flifloo** [flifloo/PyTchat#1]
After a Noryx attack, the thread of Noryx listening client raise a Invalid Token and didn't get offline
```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/flifloo/Python/PyTchat/server.py", line 54, in listen_client
    data = self.receive(self.clients[name])
  File "/usr/local/lib/python3.7/site-packages/SecureSocketService/__init__.py", line 44, in receive
    response = self.fernet.decrypt(response)
  File "/usr/local/lib/python3.7/site-packages/cryptography/fernet.py", line 74, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "/usr/local/lib/python3.7/site-packages/cryptography/fernet.py", line 92, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken```

**Comment by flifloo** [comment]
Transfer to [SecureSocketService](https://github.com/flifloo/SecureSocketService/issues/1)
